login:
  provider: avazu
  userId: 71 # todo : find it in redis
  api_url: http://api.c.avazutracking.net/performance/v2/getcampaigns.php
  username: uid
  passwd:
  token: sourceid
  policy_k: policy
  policy_v: 1,2,3,4
  params1_k:
  params1_v:
  params2_k:
  params2_v:
  # need:provider,userId,api_url,token
  pagesize: pagesize # select from db
  currentpage: page

  other_params:
    totalnum: totalnum  # the data from api turn

  result:
    resultcode: # todo
    page_path:
    totalnum_path: totalnum


affiliate:
  loop_path: campaigns[*].lps[*]
  contents:
    tracking_link: trackinglink
    country: country
    payout: payout
    preview_link: previewlink
    offer_id: _ _ cpnid
    name: _ _ cpnname
    banner: _ _ banner
    bid: _ _ bids * bid
