login:
  provider: yeahmobi
  userId: 71
  api_url: http://sync.yeahmobi.com/sync/offer/get
  username: api_id
  token: api_token
  pagesize: limit
  currentpage: page

  other_params:

  result:
      page_path: data[totalpage]
      totalnum_path: data[totalrecord]


affiliate:
  loop_path: data.data.*
  contents:
    tracking_link: tracklink
    country: countries
    payout: payout
    preview_link: preview_url
    name: name
