login:
  provider: avazu
  userId: 71
  api_url: http://api.c.avazutracking.net/performance/v2/getcampaigns.php
  username: uid
  passwd:
  token: sourceid
  policy_k: policy
  policy_v: 1,2,3,4
  params1_k:
  params1_v:
  params2_k:
  params2_v:



  api_header:

  # need:provider,userId,api_url,token

  pagesize: pagesize # select from db
  page: page






  totalnum: totalnum  # the data from api turn




content:
  provider_name: avazu
  offer_list: campaigns
  conversion_flow: convflow
  offer_id:  cpnid
  name: cpnname
  offer_description: description
  offer_type: traffictype
  carriers: carrier
  category: category
  lps: lps
  country: country
  payout: payout
  preview_url: preview_url
  tracklink: tracklink
  previewlink: previewlink
  trackinglink: trackinglink
  carrier: carrier



