login:
  provider: avazu
  userId: 71
  api_url: http://api.c.avazutracking.net/performance/v2/getcampaigns.php
  username: uid
  passwd:
  token: sourceid
  policy_k: policy
  policy_v: 1,2,3,4
  params1_k:
  params1_v:
  params2_k:
  params2_v:

  api_header:

  # need:provider,userId,api_url,token

  pagesize: pagesize # select from db
  page: page

  totalnum: totalnum  # the data from api turn




affiliate:
  loop_path: campaigns[*].lps[*]
  contents:
    trackinglink: trackinglink
    country: country
    payout: payout
    preview_link: previewlink
    offer_id: _ _ cpnid
    name: _ _ cpnname
    banner: _ _ banner
    bid: _ _ bids * bid
