login:
  provider: yeahmobi
  userId: 71
  api_url: http://sync.yeahmobi.com/sync/offer/get
  username: api_id
  token: api_token
  pagesize: limit
  page: page

  other_params:


affiliate:
  loop_path: data.data.*
  contents:
    trackinglink: tracklink
    country: countries
    payout: payout
    preview_link: preview_url
    name: name
