# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-17 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astatistics',
            name='carriers',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='astatistics',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='astatistics',
            name='conversion_flow',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='astatistics',
            name='countries',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='astatistics',
            name='exclusive',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='astatistics',
            name='offer_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='astatistics',
            name='offer_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='astatistics',
            name='payout',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='astatistics',
            name='preview_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='astatistics',
            name='tracklink',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
